name: Release Package

on:
 push:
  branches:
   - main

permissions:
 contents: read
 packages: write
 id-token: write

jobs:
 release:
   # uses: rubriclab/package/.github/workflows/release-package.yml@main
   # secrets: inherit
  runs-on: ubuntu-latest
  permissions:
   contents: read
   packages: write
   id-token: write

  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup Bun
     uses: oven-sh/setup-bun@v2
     with:
      bun-version: 'latest'

   - name: Install dependencies
     run: bun i --production

   - name: Build (if build script exists)
     run: |
      if bun run build &> /dev/null; then
        bun run build
      else
        echo "No build script found, skipping build step"
      fi

   - name: Publish to NPM Packages
     run: bun publish
     env:
      NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}